server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://172.28.17.143:3306/qxt_user?rewriteBatchedStatement=true
    username: qxt
    password: qxt@123
  batch:
    job:
      enabled: false
    initialize-schema: always
mybatis:
  mapper-locations: classpath:mybatis/mapper/**Mapper.xml
  type-aliases-package: com.lzh.demo.entity
  config-location: classpath:mybatis/mybatis-config.xml

